version: '2.2'
services:
  c1n1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: c1n1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch_c1n1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    networks:
      - clusternet
    depends_on:
      c2n1:
        condition: service_healthy
  c1n2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: c1n2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - ./elasticsearch_c1n2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - clusternet
  c2n1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: c2n1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./elasticsearch_c2n1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9201:9200
    networks:
        - clusternet
    healthcheck:
        test: ["CMD", "curl", "-f", "http://c2n1:9200"]
        interval: 15s
        timeout: 2s
        retries: 10
  c1k1:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: c1kibana
    environment:
      ELASTICSEARCH_HOSTS: http://c1n1:9200
    ports:
      - 5601:5601
    networks:
      - clusternet
  c2k1:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: c2kibana
    environment:
      ELASTICSEARCH_HOSTS: http://c2n1:9200
    ports:
      - 5602:5601
    networks:
      - clusternet

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  clusternet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"