version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch_es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./backup:/mnt/bkp:rw
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es02
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./elasticsearch_es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./backup:/mnt/bkp:rw
    networks:
      - esnet
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es03
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - ./elasticsearch_es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./backup:/mnt/bkp:rw
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  metricbeat01:
    image: docker.elastic.co/beats/metricbeat:7.13.0
    container_name: metricbeat01
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      KIBANA_HOST: http://kibana:5601
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    networks:
      - esnet

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  esnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"