#==========================  General configuration =============================
# https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-general-options.html#configuration-general
name: "metricbeat01"

#==========================  Modules configuration =============================
metricbeat.modules:
  #-------------------------------- System Module --------------------------------
  - module: system
    metricsets:
      - cpu # CPU usage
      - load # CPU load averages
      - memory # Memory usage
      - network # Network IO
      - process # Per process metrics
      - process_summary # Process summary
      - uptime # System Uptime
      - socket_summary # Socket summary
      #- core           # Per CPU core usage
      #- diskio         # Disk IO
      #- filesystem     # File system usage for each mountpoint
      #- fsstat         # File system summary metrics
      #- raid           # Raid
      #- socket         # Sockets and connection info (linux only)
      #- service        # systemd service information
    enabled: true
    period: 10s
    processes: [".*"]

    # Configure the mount point of the host’s filesystem for use in monitoring a host from within a container
    #system.hostfs: "/hostfs"

    # Configure the metric types that are included by these metricsets.
    cpu.metrics: ["percentages", "normalized_percentages"] # The other available option is ticks.
    core.metrics: ["percentages"] # The other available option is ticks.

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Boolean flag to enable or disable the output module.
  #enabled: true

  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify and additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: "${ELASTICSEARCH_HOSTS:localhost:9200}"
  username: "${ELASTICSEARCH_USERNAME:}"
  password: "${ELASTICSEARCH_PASSWORD:}"

setup.kibana:
  hosts: "${KIBANA_HOSTS:localhost:5061}"
